In [1]:
import gym
import numpy as np
import matplotlib.pyplot as plt
#from gym.envs.registration import register

In [2]:
#register(
#    id='FrozenLake-v0',
#    entry_point='gym.envs.toy_text:FrozenLakeEnv',
#    kwargs={'map_name': '4x4',
#            'is_slippery': True}
#)
env = gym.make('FrozenLake-v0')

In [3]:
Q = np.zeros([env.observation_space.n,env.action_space.n])
learning_rate = .5
dis = .99
num_episodes = 2000
rList = []

In [4]:
for i in range(num_episodes):
    state = env.reset()
    rAll = 0
    done = False
    
    while not done:
        action =  np.argmax(Q[state, :] + np.random.randn(1, env.action_space.n) / (i+1))
        new_state, reward, done,_ = env.step(action)
        Q[state,action] = (1- learning_rate) * Q[state,action] \
            + learning_rate*(reward + dis * np.max(Q[new_state, :]))
        rAll += reward
        state = new_state
    rList.append(rAll)

In [ ]:
print("Score over time:" + str(sum(rList)/num_episodes))
print("Final Q-Table Values")
print(Q)
plt.bar(range(len(rList)), rList, color="blue")
plt.show()

Score over time:0.478
Final Q-Table Values
[[  4.60103381e-02   5.20254330e-02   4.89250808e-01   4.64203279e-02]
 [  3.55709096e-03   1.24466065e-03   1.48960416e-02   4.82373371e-01]
 [  1.24095773e-02   3.86531783e-01   2.16170231e-02   5.36148348e-04]
 [  0.00000000e+00   0.00000000e+00   0.00000000e+00   4.03945991e-01]
 [  5.17522227e-01   1.85693310e-02   1.41321235e-02   4.51104817e-03]
 [  0.00000000e+00   0.00000000e+00   0.00000000e+00   0.00000000e+00]
 [  1.84147432e-01   1.46476741e-03   1.65631302e-03   1.99315459e-03]
 [  0.00000000e+00   0.00000000e+00   0.00000000e+00   0.00000000e+00]
 [  6.68593643e-03   1.79341018e-02   7.08106652e-03   6.69200028e-01]
 [  0.00000000e+00   7.06610304e-01   0.00000000e+00   1.06448929e-02]
 [  7.38350188e-01   0.00000000e+00   0.00000000e+00   0.00000000e+00]
 [  0.00000000e+00   0.00000000e+00   0.00000000e+00   0.00000000e+00]
 [  0.00000000e+00   0.00000000e+00   0.00000000e+00   0.00000000e+00]
 [  0.00000000e+00   0.00000000e+0